const path = require('path');
const express = require('express');
const Userrouter = express.Router();
const rootdir = require('../utils/pathUtil');
const homecontroller = require('../controller/home');
Userrouter.get("/",homecontroller.getLogin);
 Userrouter.get("/home",homecontroller.getHome);
  Userrouter.get("/Login",homecontroller.getLogin);
Userrouter.get("/home/form",homecontroller.getForm);
Userrouter.get("/joblisting",homecontroller.getJoblisting);
Userrouter.get("/postjob",homecontroller.getPostjob);
exports.Userrouter = Userrouter;
